### ISSUE TITLE
timezone_id not being set 

### ISSUE THREAD

**Issue by gitanupam** [cronofy/pycronofy#32]
Can't seem to get the results back in the right timezone even after setting it as required.

```
events = cronofy.read_events(calendar_ids=('CAL_ID',),from_date=from_date, to_date=to_date, tzid='Asia/Kolkata')

print (events.json())

```
The returning json always has events in the UTC timezone. Does it mean that `tzid` is only for the input (`from_date`, `to_date`) and the returned values will always be in UTC?

(Also asked on [SO](https://stackoverflow.com/q/49685262/1526703) but it doesn't seem to have a tag for Cronofy or this library)

**Comment by gshutler** [comment]
The `tzid` parameter relates to the restriction of events for the request, to get richer time information in the response you need to request `localized_times`:

```py
events = cronofy.read_events(calendar_ids=('CAL_ID',),
                             from_date=from_date,
                             to_date=to_date,
                             tzid='Asia/Kolkata',
                             localized_times=True)
```

Also [responded on SO](https://stackoverflow.com/a/49687007/6369).
