### ISSUE TITLE
data_center supplied to Client not used in all API calls

### ISSUE THREAD

**Issue by haavikko** [cronofy/pycronofy#41]
Several API calls do not use API_REGION_FORMAT setting, even when cronofy client is configured with data_center= 'de'  option. Several methods in client.py use settings.API_BASE_URL directly instead.

Workaround: Change API_BASE_URL setting in settings.py. This works, if the default data center need not be used at all.

**Comment by stephenbinns** [comment]
This is fixed in 1.1.7
