### ISSUE TITLE
requests/pytz are not marked as dependencies

### ISSUE THREAD

**Issue by ChrisBurch** [cronofy/pycronofy#45]
Requests (and pytz) don't seem to be added to the dependencies when installing through pypi, causing errors if you don't have those packages already installed in your repo. 

Exception trying to import pycronofy: 
```
  File "/path/to/user_code.py", line 5, in <module>
    import pycronofy
  File "/Users/......./python3.7/site-packages/pycronofy/__init__.py", line 1, in <module>
    from pycronofy.client import Client  # noqa: F401
  File "/Users/......./python3.7/site-packages/pycronofy/client.py", line 12, in <module>
    from pycronofy.request_handler import RequestHandler
  File "/Users/......./python3.7/site-packages/pycronofy/request_handler.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Output from `pipenv graph`:
```
PyCronofy==1.3.0
  - future [required: Any, installed: 0.17.1]
```

**Comment by gshutler** [comment]
Not too familiar with Python but my research suggested this was because the core dependencies weren't specified in `setup.py`'s `install_requires`.

1.4.0 has been released which should resolve this.

Thanks for the report @ChrisBurch - let us know if you have any more problems.

**Comment by ChrisBurch** [comment]
That did the trick, thanks @gshutler for the quick fix!
