### ISSUE TITLE
Cronofy date obj/dict for creating events not supported

### ISSUE THREAD

**Issue by benjaminjones** [cronofy/pycronofy#5]
Cronofy has the feature in their docs to create an event with:

```
The start time can be provided as a simple Time or Date string or an object with two attributes, time and tzid:
{
  "time": "2014-08-05T17:00:00Z",
  "tzid": "Europe/Paris"
}
```
It seems the `dict` structure is not supported in `upsert_event` for the `start` and `end` values.

**Comment by stephenbinns** [comment]
Fixed in `1.1.1` thanks for the detailed bug report
