### ISSUE TITLE
Batch upsert fails when provided with datetimes

### ISSUE THREAD

**Issue by ChrisBurch** [cronofy/pycronofy#76]
Calling `BatchBuilder#upsert_event` using datetimes for `start`/`end` throws a json serialization error, since the datetimes aren't formatted into strings

**Comment by Grajo** [comment]
Hi @ChrisBurch, we've just released version 1.9.5 which should sort this out 👍

If you have any problems, please let us know at [support@cronofy.com](mailto:support@cronofy.com)
