### ISSUE TITLE
Batch requests fail due to missing "batch" array

### ISSUE THREAD

**Issue by ChrisBurch** [cronofy/pycronofy#78]
`Client#batch` sends the batched requests directly as a list in the POST body, instead of providing an object with the list keyed under `batch` as expected per [docs](https://docs.cronofy.com/developers/api/batch/#example-request), causing batched requests to fail.

**Comment by Grajo** [comment]
Hi @ChrisBurch, we've just released version 1.9.5 which should sort this out 👍

If you have any problems, please let us know at [support@cronofy.com](mailto:support@cronofy.com)

**Comment by ChrisBurch** [comment]
Awesome, thanks @Grajo. 1.9.5 is working well for me, thanks for the quick turnaround and release on this!
