### ISSUE TITLE
how to fix `Callback URL must not be an example or local URL`

### ISSUE THREAD

**Issue by kev26** [cronofy/pycronofy#86]
I just want to test sending emails including meetings created by Coronofy in my local, but I am stuck in the step call back URL with the following error: `Callback URL must not be an example or local URL`

this is URL raises the error: `http://localhost:8000/clubs/cronofy/callback/`

**Comment by AdamWhittingham** [comment]
The callback URL needs to enable our servers to send messages to the machine running your code, so local addresses like `localhost` aren't allowed.
We [have some tips on using ngrok for local development](https://docs.cronofy.com/developers/push-notifications/#testing-locally) to quickly and easily get a URL pointing to your local setup.

If you have any further questions, please contact us via [our support team](https://docs.cronofy.com/support/) who will be able to assist.
